from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class ScenarioType(StrEnum):
    GREENFIELD = "GREENFIELD"
    BROWNFIELD = "BROWNFIELD"
    AMBIGUOUS = "AMBIGUOUS"


class WorkflowStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    WAITING_FOR_CLARIFICATION = "WAITING_FOR_CLARIFICATION"
    WAITING_FOR_REQUIREMENT_APPROVAL = "WAITING_FOR_REQUIREMENT_APPROVAL"
    DESIGNING = "DESIGNING"
    PLANNING = "PLANNING"
    WAITING_FOR_ARCHITECTURE_APPROVAL = "WAITING_FOR_ARCHITECTURE_APPROVAL"
    INITIALIZING_WORKSPACE = "INITIALIZING_WORKSPACE"
    ANALYZING_REPOSITORY = "ANALYZING_REPOSITORY"
    IMPLEMENTING = "IMPLEMENTING"
    VALIDATING = "VALIDATING"
    RETRYING = "RETRYING"
    REPLANNING = "REPLANNING"
    ROLLING_BACK = "ROLLING_BACK"
    WAITING_FOR_RELEASE_APPROVAL = "WAITING_FOR_RELEASE_APPROVAL"
    READY = "READY"
    READY_WITH_CONDITIONS = "READY_WITH_CONDITIONS"
    NOT_READY = "NOT_READY"
    SAFE_STOPPED = "SAFE_STOPPED"
    FAILED = "FAILED"


class ApprovalGate(StrEnum):
    REQUIREMENT = "REQUIREMENT"
    ARCHITECTURE_AND_PLAN = "ARCHITECTURE_AND_PLAN"
    HIGH_RISK_CHANGE = "HIGH_RISK_CHANGE"
    RELEASE = "RELEASE"
    ROLLBACK = "ROLLBACK"


class ApprovalAction(StrEnum):
    APPROVE = "APPROVE"
    APPROVE_WITH_CONDITIONS = "APPROVE_WITH_CONDITIONS"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECT = "REJECT"


class FailureCategory(StrEnum):
    STRUCTURED_OUTPUT_ERROR = "STRUCTURED_OUTPUT_ERROR"
    IMPLEMENTATION_DEFECT = "IMPLEMENTATION_DEFECT"
    TEST_DEFECT = "TEST_DEFECT"
    REQUIREMENT_AMBIGUITY = "REQUIREMENT_AMBIGUITY"
    ARCHITECTURE_MISMATCH = "ARCHITECTURE_MISMATCH"
    ENVIRONMENT_FAILURE = "ENVIRONMENT_FAILURE"
    DEPENDENCY_FAILURE = "DEPENDENCY_FAILURE"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    CRITICAL_SECURITY_FAILURE = "CRITICAL_SECURITY_FAILURE"
    DOCUMENTATION_FAILURE = "DOCUMENTATION_FAILURE"
    INCONSISTENT_STATE = "INCONSISTENT_STATE"
    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ScriptedScenario(StrEnum):
    HAPPY_PATH = "HAPPY_PATH"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    REQUIREMENT_REJECTED = "REQUIREMENT_REJECTED"
    ARCHITECTURE_CHANGE_REQUESTED = "ARCHITECTURE_CHANGE_REQUESTED"
    CODING_RETRY_THEN_PASS = "CODING_RETRY_THEN_PASS"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    VALIDATION_FAILURE = "VALIDATION_FAILURE"
    ROLLBACK_REQUIRED = "ROLLBACK_REQUIRED"


class AgentInput(BaseModel):
    workflow_id: str
    scenario_type: ScenarioType
    scripted_scenario: ScriptedScenario = ScriptedScenario.HAPPY_PATH
    retry_number: int = Field(default=0, ge=0)
    context: dict[str, Any] = Field(default_factory=dict)
